name: Zéphyr CI/CD

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Check that the Dart source code is correctly formatted.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run dartfmt
        id: yapf
        uses: docker://google/dart:2.8.4
        with:
          args: dartfmt -n --set-exit-if-changed -l 120 .

  test:
    runs-on: ubuntu-18.04
    name: Test the project.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Zéphyr
        uses: ./
        id: zephyr_test
        with:
          args: "test"

  release:
    runs-on: ubuntu-18.04
    name: Create a release
    needs: [lint, test]
    if: github.event_name == 'push' && github.base_ref == 'master' || contains(github.ref, 'cicd/')
    steps:
      - name: Create a release for Zéphyr
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          draft: true
          prerelease: false
